### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.97 GiB. GPU 2 has a total capacty of 39.43 GiB of which 982.31 MiB is free. Including non-PyTorch memory, this process has 38.47 GiB memory in use. Of the allocated memory 28.76 GiB is allocated by PyTorch, and 7.31 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by mayilin0714** [Ucas-HaoranWei/Vary#18]
您好，我在运行deepspeed   vary/train/train_qwen_vary.py 时出现CUDA out of memory的问题，在调整了一些参数之后仍无法解决这个问题，以下是我的参数设置：

deepspeed   vary/train/train_qwen_vary.py \
            --deepspeed /home/mayilin/workspace/code/Vary/Vary-master/zero_config/zero2.json \
            --model_name_or_path /data01/mayilin_data/llava/vary-llava80k \
            --vision_tower /home/mayilin/workspace/code/LLaVA/openai/clip-vit-large-patch14-336 \
            --freeze_vision_tower True \
            --freeze_lm_model False \
            --vision_select_layer  -2 \
            --use_im_start_end True \
            --bf16 True \
            --per_device_train_batch_size 1 \
            --per_device_eval_batch_size 1 \
            --gradient_accumulation_steps 1 \
            --evaluation_strategy "no" \
            --save_strategy "steps" \
            --save_steps 5000 \
            --save_total_limit 1 \
            --weight_decay 0. \
            --warmup_ratio 0.03 \
            --lr_scheduler_type "cosine" \
            --logging_steps 1 --tf32 True \
            --model_max_length 4096 \
            --gradient_checkpointing True \
            --dataloader_num_workers 4 \
            --report_to none \
            --num_train_epochs 1 \
            --learning_rate 5e-5 \
            --datasets  llava_merge_mix665k_latex_wollavapre+llava_v1_5_mix665k_14669 \
            --output_dir /data01/mayilin_data/vary_checkpoints/ \

请问应该如何解决这个问题呢？

**Comment by Ucas-HaoranWei** [comment]
你的显卡多大显存，zero2爆显存的话，试试zero3，
另外，后续我们会考虑放出一个小点的模型（1.x B），让大家可以在小显存的机器上跑

**Comment by mayilin0714** [comment]
非常感谢您的回答。这是我的显卡情况
<img width="549" alt="image" src="https://github.com/Ucas-HaoranWei/Vary/assets/71692462/a0338a3d-e1ca-4062-b3ab-b439e23aa88b">


在使用了zero3.json后我又遇到了如下的问题：

AssertionError: {'id': 833, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 4096), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {820}, 'ds_tensor.shape': torch.Size([0])}

zero3.json设置如下：
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto"
    },
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e5,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e5,
        "stage3_max_reuse_distance": 1e5,
        "stage3_gather_16bit_weights_on_model_save": true
    }
}

**Comment by crackso** [comment]
这8卡够猛了，这都爆现存，你放了多大的输入

**Comment by mayilin0714** [comment]
https://github.com/huggingface/transformers/pull/26024￼
fix _resize_token_embeddings will set lm head size to 0 when enabled deepspeed zero3 by kai01ai · Pull Request #26024 · huggingface/transformers
github.com
我按照上述的解决方案已经解决了这个问题。

**Comment by GITMrzk** [comment]
> 你的显卡多大显存，zero2爆显存的话，试试zero3， 另外，后续我们会考虑放出一个小点的模型（1.x B），让大家可以在小显存的机器上跑

@Ucas-HaoranWei ,您这边训练的时候用了什么样配置的机器呢？我看readme里没有详细写。我这边80g的显存batchsize1，也一样爆掉。
